import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import { useState } from 'react'
import {BsSearch} from 'react-icons/bs'
import Weather from '../components/Weather'
import Spinner from '../components/Spinner'

export default function Home() {

  const [city, setCity] = useState('')
  const [weather, setWeather] = useState({})
  const [loading, setLoading] = useState(false)

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=imperial&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`
  
  const fetchWeather = (e) => {
    e.preventDefault()
    setLoading(true)
    axios.get(url).then((response) => {
      setWeather(response.data)
      // console.log(response.data)
    })
    setCity('')
    setLoading(false)
  }

  if(loading) {
    return <Spinner />
  } else {
    return (
      <div>
        <Head>
          <title>ArtofNuel Nextjs Weather App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        {/* Overlay */}
        <div className='absolute top-0 left-0 right-0 bottom-0 bg-black/40 z-[1]' />
  
        {/* BKG IMage */}
        <Image
          src={'https://images.unsplash.com/photo-1665114839470-f57f75b78f82?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=727&q=80'}
          alt='/'
          layout='fill'
          className='object-cover object-center'
          />
  
        {/* Search */}
        <div className='relative flex justify-between items-center max-w-4xl w-full mx-auto mt-8 px-8 text-white z-10'>
          <form onSubmit={fetchWeather} className='flex justify-between items-center w-full p-3 mx-auto bg-transparent border border-gray-200 text-white rounded'>
            <div>
              <input 
              onChange={(e) => setCity(e.target.value)}
              className='w-[300px] md:w-[600px] bg-transparent border-none focus:outline-none text-2xl placeholder:text-white' 
              type="text" 
              placeholder='Seach a city' 
              />
            </div>
              <button onClick={fetchWeather}><BsSearch size={25} /></button>
          </form>
        </div>
        {/* Weather Section */}
        {weather.main && <Weather data={weather}/>}
      </div>
    )
  }

  
}
